### ISSUE TITLE
Bad

### ISSUE THREAD

**Issue by cameronlund4** [EastRobotics/2616J#4]
Please fix

**Comment by raysarebest** [comment]
I saw this scroll across my activity feed with the tag "help wanted", so I thought I'd comment. I don't have a ROBOTC compiler anymore, but if you can describe the problem you're having, I'd be happy to take a look

**Comment by bb00** [comment]
It’s ok Michael, Cameron is just meme-ing along.

**Comment by bb00** [comment]
I'm going to close this because I really don't feel like having a fake issue in my feed constantly. Au revoir!
